name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install --save-dev jest ts-jest @types/jest jest-sonar-reporter

    - name: Build project
      run: npm run build

    - name: Run tests and generate coverage
      run: npm test -- --coverage
      env:
        CI: true

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: dist/

    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: test-report.xml

    - name: Upload code coverage reports
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage
        path: coverage/

    - name: Generate  Summary
      id: run_summary
      run: |
        echo "## Run Summary" >> $GITHUB_STEP_SUMMARY
        echo "- Artifact: artifact" >> $GITHUB_STEP_SUMMARY
        echo "- Version: version" >> $GITHUB_STEP_SUMMARY
        echo "- Repository URL: repo" >> $GITHUB_STEP_SUMMARY
